# Generated by Django 5.2.4 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_description', models.TextField()),
                ('asset_purchase_date', models.DateField()),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_status', models.TextField(max_length=150)),
                ('asset_id', models.IntegerField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
