# Generated by Django 5.2.4 on 2025-11-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='Employees.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(default='new', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
